import React, { useId } from "react";

import { MASCOT_ARTWORK, type MascotNode } from "./mascotArtwork";

function renderNodes(nodes: readonly MascotNode[]): React.ReactNode[] {
  return nodes.map(([tag, props, children], index) =>
    React.createElement(tag, { key: index, ...props }, children ? renderNodes(children) : undefined),
  );
}

/**
 * Two bright bands, slanted like the glints, parked left of the lenses. The
 * sweep animation slides them across, clipped to the lenses.
 */
const SWEEP_BANDS = ["M300 400 L360 400 L260 560 L200 560 Z", "M385 400 L405 400 L305 560 L285 560 Z"];
/**
 * How the mascot moves, for brand moments only (DESIGN.md § Motion):
 *
 * - `sweep`: bands of light cross the lenses every few seconds (About).
 * - `commits`: the crest's commits light amber one after another, tail to
 *   HEAD, every few seconds (the welcome screen).
 */
export type MascotMotion = "sweep" | "commits";

export interface MascotProps {
  /**
   * Plays the welcome's one-time entrance before the motion: the outline
   * draws itself, the colours fill in and the commits pop in, tail to HEAD.
   */
  entrance?: boolean;
  /** `body` shows the whole mascot; `head` crops it to the head, crest to snout tip. */
  variant?: "body" | "head";
  motion?: MascotMotion;
  className?: string;
}

/**
 * The GitOdile mascot, drawn inline from `mascotArtwork.ts` (generated by
 * `scripts/icons/mascot.mjs`) so its green body can follow the theme through
 * `--mascot-fill` (primitives.css). Always decorative: the text beside it
 * names the screen or dialog.
 */
export function Mascot({ variant = "body", motion, entrance = false, className }: MascotProps) {
  const artwork = MASCOT_ARTWORK[variant];
  const clipId = `${useId()}-glasses`;
  return (
    <svg
      className={["gitodile-mascot", `gitodile-mascot--${variant}`, motion && `gitodile-mascot--${motion}`, entrance && "gitodile-mascot--enter", className]
        .filter(Boolean)
        .join(" ")}
      viewBox={artwork.viewBox}
      aria-hidden="true"
      focusable="false"
    >
      {renderNodes(artwork.nodes)}
      {motion === "sweep" && (
        <>
          <clipPath id={clipId}>
            <path d={artwork.glasses} />
          </clipPath>
          <g clipPath={`url(#${clipId})`}>
            <g className="gitodile-mascot__shine">
              {SWEEP_BANDS.map((d) => (
                <path key={d} d={d} />
              ))}
            </g>
          </g>
        </>
      )}
    </svg>
  );
}
