import React, { useId } from "react";

import { MASCOT_ARTWORK, type MascotNode } from "./mascotArtwork";

function renderNodes(nodes: readonly MascotNode[]): React.ReactNode[] {
  return nodes.map(([tag, props, children], index) =>
    React.createElement(tag, { key: index, ...props }, children ? renderNodes(children) : undefined),
  );
}

/**
 * Two bright bands, slanted like the glints, parked left of the lenses. The
 * sweep animation slides them across, clipped to the glasses.
 */
const SWEEP_BANDS = ["M450 290 L520 290 L366 500 L296 500 Z", "M540 290 L560 290 L406 500 L386 500 Z"];
/** A four-point star, centred on its own origin; the greet animation places it on the right lens. */
const STAR = "M0 -95 C12 -12 12 -12 95 0 C12 12 12 12 0 95 C-12 12 -12 12 -95 0 C-12 -12 -12 -12 0 -95 Z";

/**
 * How the glasses move, for brand moments only (DESIGN.md § Motion):
 *
 * - `sweep`: bands of light cross the lenses every few seconds (About).
 * - `greet`: the glasses lift and settle once, then a star glints on the
 *   right lens every few seconds (the first Home visit).
 * - `glint`: repeat visits keep only the periodic star.
 */
export type MascotMotion = "sweep" | "greet" | "glint";

export interface MascotProps {
  /** `body` for anything shown larger than a small square icon; `head` below. */
  variant?: "body" | "head";
  motion?: MascotMotion;
  className?: string;
}

/**
 * The GitOdile mascot, drawn inline from `mascotArtwork.ts` (generated by
 * `scripts/icons/mascot.mjs`) so its lime fill can follow the theme through
 * `--mascot-fill` (primitives.css). Always decorative: the text beside it
 * names the screen or dialog.
 */
export function Mascot({ variant = "body", motion, className }: MascotProps) {
  const artwork = MASCOT_ARTWORK[variant];
  const clipId = `${useId()}-glasses`;
  return (
    <svg
      className={["gitodile-mascot", `gitodile-mascot--${variant}`, motion && `gitodile-mascot--${motion}`, className]
        .filter(Boolean)
        .join(" ")}
      viewBox={artwork.viewBox}
      aria-hidden="true"
      focusable="false"
    >
      {renderNodes(artwork.nodes)}
      {motion === "sweep" && (
        <>
          <clipPath id={clipId}>
            <path d={artwork.glasses} />
          </clipPath>
          <g clipPath={`url(#${clipId})`}>
            <g className="gitodile-mascot__shine">
              {SWEEP_BANDS.map((d) => (
                <path key={d} d={d} />
              ))}
            </g>
          </g>
        </>
      )}
      {(motion === "greet" || motion === "glint") && <path className="gitodile-mascot__star" d={STAR} />}
    </svg>
  );
}
