// Generated by scripts/icons/mascot.mjs. Do not edit; run `node scripts/icons/mascot.mjs`.
//
// The mascot as SVG element nodes with React prop names. Classed groups:
// `gitodile-mascot__fill` is the lime fill the in-app mark recolours per theme,
// `gitodile-mascot__glasses` the strap, frame and glints that move together, and
// `gitodile-mascot__glints` the two white glints.

export type MascotNode = readonly [tag: string, props: Readonly<Record<string, string | number>>, children?: readonly MascotNode[]];

export interface MascotArtwork {
  readonly viewBox: string;
  readonly nodes: readonly MascotNode[];
  /** Outline of the sunglasses, for clipping the shine across the lenses. */
  readonly glasses: string;
}

export const MASCOT_ARTWORK: Readonly<Record<"body" | "head", MascotArtwork>> = {
  "body": {
    "viewBox": "68 176 1400 700",
    "nodes": [
      [
        "g",
        {
          "className": "gitodile-mascot__fill",
          "fill": "#a8f442",
          "stroke": "#000000",
          "strokeWidth": 50,
          "strokeLinejoin": "round",
          "strokeLinecap": "round"
        },
        [
          [
            "rect",
            {
              "x": 1000,
              "y": 660,
              "width": 112,
              "height": 170,
              "rx": 28
            }
          ],
          [
            "path",
            {
              "d": "M118 580 C118 500 158 445 208 445 C250 445 272 482 296 516 C324 490 336 478 352 478 C370 478 390 490 398 500 C425 462 444 432 462 432 C482 432 505 446 515 458 C548 395 568 355 590 355 C615 355 640 375 655 392 C660 300 720 232 800 232 C835 232 862 250 875 272 C890 245 925 222 962 222 C1030 222 1080 270 1095 330 L1100 352 C1180 356 1270 358 1340 356 C1405 354 1434 390 1434 445 C1434 495 1414 540 1388 572 C1335 650 1250 712 1150 732 L950 731 Q920 731 920 761 L920 800 Q920 830 890 830 L770 830 Q740 830 740 800 L740 760 Q740 730 710 730 L520 730 Q490 730 490 760 L490 800 Q490 830 460 830 L320 830 Q290 830 290 800 L290 752 C200 732 125 670 118 575 Z"
            }
          ],
          [
            "path",
            {
              "fill": "none",
              "strokeWidth": 48,
              "d": "M885 540 C960 588 1055 600 1175 594 C1255 590 1330 572 1392 555"
            }
          ]
        ]
      ],
      [
        "g",
        {
          "className": "gitodile-mascot__glasses"
        },
        [
          [
            "path",
            {
              "fill": "none",
              "stroke": "#000000",
              "strokeWidth": 50,
              "strokeLinecap": "round",
              "d": "M655 378 H780"
            }
          ],
          [
            "path",
            {
              "fill": "#000000",
              "stroke": "#000000",
              "strokeWidth": 16,
              "strokeLinejoin": "round",
              "d": "M765 345 L1250 300 C1262 300 1266 318 1258 340 C1250 420 1200 485 1140 485 C1085 485 1048 455 1035 420 L1015 422 C1000 460 950 498 885 498 C815 498 770 440 765 345 Z"
            }
          ],
          [
            "g",
            {
              "className": "gitodile-mascot__glints",
              "fill": "#ffffff"
            },
            [
              [
                "path",
                {
                  "d": "M920 353 L955 351 L875 458 L843 452 Z"
                }
              ],
              [
                "path",
                {
                  "d": "M1175 338 L1212 335 L1133 441 L1100 435 Z"
                }
              ]
            ]
          ]
        ]
      ],
      [
        "circle",
        {
          "cx": 1335,
          "cy": 450,
          "r": 27,
          "fill": "#000000"
        }
      ]
    ],
    "glasses": "M765 345 L1250 300 C1262 300 1266 318 1258 340 C1250 420 1200 485 1140 485 C1085 485 1048 455 1035 420 L1015 422 C1000 460 950 498 885 498 C815 498 770 440 765 345 Z"
  },
  "head": {
    "viewBox": "545 170 915 610",
    "nodes": [
      [
        "g",
        {
          "className": "gitodile-mascot__fill",
          "fill": "#a8f442",
          "stroke": "#000000",
          "strokeWidth": 50,
          "strokeLinejoin": "round",
          "strokeLinecap": "round"
        },
        [
          [
            "path",
            {
              "d": "M655 392 C660 300 720 232 800 232 C835 232 862 250 875 272 C890 245 925 222 962 222 C1030 222 1080 270 1095 330 L1100 352 C1180 356 1270 358 1340 356 C1405 354 1434 390 1434 445 C1434 495 1414 540 1388 572 C1335 650 1250 712 1150 732 L840 732 C680 732 588 662 588 560 C588 492 614 438 655 392 Z"
            }
          ],
          [
            "path",
            {
              "fill": "none",
              "strokeWidth": 48,
              "d": "M885 540 C960 588 1055 600 1175 594 C1255 590 1330 572 1392 555"
            }
          ]
        ]
      ],
      [
        "g",
        {
          "className": "gitodile-mascot__glasses"
        },
        [
          [
            "path",
            {
              "fill": "none",
              "stroke": "#000000",
              "strokeWidth": 50,
              "strokeLinecap": "round",
              "d": "M605 378 H780"
            }
          ],
          [
            "path",
            {
              "fill": "#000000",
              "stroke": "#000000",
              "strokeWidth": 16,
              "strokeLinejoin": "round",
              "d": "M765 345 L1250 300 C1262 300 1266 318 1258 340 C1250 420 1200 485 1140 485 C1085 485 1048 455 1035 420 L1015 422 C1000 460 950 498 885 498 C815 498 770 440 765 345 Z"
            }
          ],
          [
            "g",
            {
              "className": "gitodile-mascot__glints",
              "fill": "#ffffff"
            },
            [
              [
                "path",
                {
                  "d": "M920 353 L955 351 L875 458 L843 452 Z"
                }
              ],
              [
                "path",
                {
                  "d": "M1175 338 L1212 335 L1133 441 L1100 435 Z"
                }
              ]
            ]
          ]
        ]
      ],
      [
        "circle",
        {
          "cx": 1335,
          "cy": 450,
          "r": 27,
          "fill": "#000000"
        }
      ]
    ],
    "glasses": "M765 345 L1250 300 C1262 300 1266 318 1258 340 C1250 420 1200 485 1140 485 C1085 485 1048 455 1035 420 L1015 422 C1000 460 950 498 885 498 C815 498 770 440 765 345 Z"
  }
};
