import { act, cleanup, render, screen } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { afterEach, expect, it, vi } from "vitest";
import { LanguageProvider } from "../../i18n";
import type { AccountsPort } from "../accounts";
import { GitLabTokenSection } from "./GitLabTokenSection";
afterEach(() => { cleanup(); localStorage.clear(); });
it("shows a catalog read failure and retries locally without checking the provider", async () => {
  const readCatalog = vi.fn().mockRejectedValueOnce(new Error("read failed")).mockResolvedValue({ providers: [{ id: "gitlab", host: "gitlab.com" }], accounts: [], busy: false });
  const check = vi.fn();
  const accountPort: AccountsPort = { readCatalog, check, readProject: vi.fn(), selectProject: vi.fn() };
  render(<LanguageProvider><GitLabTokenSection port={{ add: vi.fn(), remove: vi.fn(), cancel: vi.fn() }} accountPort={accountPort} /></LanguageProvider>);
  expect(await screen.findByRole("alert")).toHaveTextContent("Couldn't read saved connections");
  expect(screen.queryByRole("button", { name: "Add a token" })).not.toBeInTheDocument();
  await userEvent.click(screen.getByRole("button", { name: "Retry reading connections" }));
  expect(await screen.findByRole("button", { name: "Add a token" })).toBeEnabled();
  expect(screen.queryByRole("alert")).not.toBeInTheDocument();
  expect(readCatalog).toHaveBeenCalledTimes(2);
  expect(check).not.toHaveBeenCalled();
});
it("clears the masked token before native ingestion without any glab dependency", async () => {
  let finish!: (id: string) => void;
  const add = vi.fn(() => new Promise<string>(resolve => { finish = resolve; }));
  const accountPort: AccountsPort = { readCatalog: async () => ({ providers: [{ id: "gitlab", host: "gitlab.com" }], accounts: [], busy: false }), check: vi.fn(), readProject: vi.fn(), selectProject: vi.fn() };
  render(<LanguageProvider><GitLabTokenSection port={{ add, remove: vi.fn(), cancel: vi.fn() }} accountPort={accountPort} /></LanguageProvider>);
  await userEvent.click(screen.getByRole("button", { name: "Add a token" }));
  const input = screen.getByLabelText("Personal access token");
  expect(input).toHaveAttribute("type", "password");
  await userEvent.type(input, "fixture-secret-123456");
  await userEvent.click(screen.getByRole("button", { name: "Check and connect" }));
  expect(input).toHaveValue("");
  expect(add).toHaveBeenCalledWith("fixture-secret-123456", expect.any(String));
  expect(document.body.textContent).not.toContain("fixture-secret");
  expect(screen.getByText(/read_api/)).toHaveTextContent("write_repository");
  await act(async () => finish("gitlab:token.42"));
  expect(await screen.findByText("Token connection verified and saved.")).toBeVisible();
});
